low = ["traitor", "florida_man", "paradox_clone", "cortical_borer", "obsessed", "traitor/contractor", "abductor/scientist/onemanteam"]
medium = ["heretic", "bloodsucker", "cortical_borer/hivemind", "reverant", "nightmare", "slasher"]
high = ["cult", "rev/head", "wizard", "clock_cultist", "ninja"]
