//TODO: make these functional
// TRAIT_IMPACTIMMUNE
// TRAIT_FAST_COOLDOWNS
// TRAIT_DARKSPAWN_LIGHTRES
// TRAIT_DARKSPAWN_CREEP
// TRAIT_DARKSPAWN_DEVOURED
// TRAIT_DARKSPAWN_PSIBLOCK
// TRAIT_DARKSPAWN_BUFFALLIES
// TRAIT_DARKSPAWN_UNDYING
// ANTAG_RESOURCE_DARKSPAWN

// TODO: darkspawn.dm

//TODO: ensure TRAIT_FAST_COOLDOWNS works

//six quadrillion other things I forgot
